server:
  port: 8080

spring:
  # --- Configuración de la Base de Datos e JPA ---
  datasource:
    url: jdbc:h2:mem:auctiondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: tu_correo@gmail.com
    password: tu_contraseña_de_aplicacion
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # --- Configuración de Mailtrap (Agrupada dentro de spring) ---
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: ${SMTP_USER:apikey}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: ${SMTP_AUTH:true}
          starttls:
            enable: ${SMTP_STARTTLS:true}
          from: ${SMTP_FROM:abast.no.responda@gmail.com}

logging:
  level:
    org.springframework: INFO